services:
  vote:
    image: dockersamples/examplevotingapp_vote
    container_name: vote-app
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier

  result:
    image: dockersamples/examplevotingapp_result
    container_name: result-app
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: dockersamples/examplevotingapp_worker
    container_name: worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: vote-redis
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    container_name: vote-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db_data:

networks:
  front-tier:
  back-tier: