services:
  mongodb:
    image: mongo:latest
    container_name: p3-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: p3-node
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: